config/routes.rb
Labbook::Application.routes.draw do

  resources :albums, only: [:index, :show] do
    collection do
      post 'replace_all_snapshots'
    end
    member do
      get 'report'
    end
    resources :snapshots, except: [:index]
  end
end

app/models/album.rb
require 'uuidtools'

class Album < ActiveRecord::Base
  self.primary_key = "uuid"

  has_many :snapshots

  before_create { |album| album.uuid = UUIDTools::UUID.random_create.to_s }

  def self.token(source, user_id)
    Digest::SHA1.hexdigest("#{source}-#{user_id}")
  end

  def replace_all_snapshots(source_album)
    self.transaction do
      snapshots.destroy_all
      new_snapshots = source_album.snapshots.map { |s| s.dup }
      self.snapshots = new_snapshots
      save!
    end
  end
end

app/models/snapshot.rb
class Snapshot < ActiveRecord::Base
  attr_reader :content_remote_url
  attr_reader :annotated_snapshot_url

  belongs_to :album

  has_attached_file :content,
    styles: { medium: "500x500>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"

  has_attached_file :annotated_content,
    styles: { medium: "500x500>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"

  def content_remote_url=(url_str)
    self.content = URI.parse(url_str)
    @content_remote_url = url_str
  end

  def annotated_snapshot_url=(url_str)
    (self.annotated_content = URI.parse(url_str)) rescue nil
    @annotated_snapshot_url = url_str
  end

  def dup
    clone = super
    # Fix paperclip attachments:
    clone.content = content
    clone.annotated_content = annotated_content
    clone
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  layout 'report', only: [:report]

  before_action :set_album, except: [:replace_all_snapshots]
  skip_before_filter  :verify_authenticity_token, only: [:replace_all_snapshots]

  # GET /albums
  def index
    if @album
      if params[:todo] && params[:todo] == "new"
        redirect_to new_album_snapshot_path(@album)
      elsif params[:todo] && params[:todo] == "create" && params[:source_url]
        # Create a snapshot from the source url
        @snapshot = Snapshot.create!(content_remote_url: params[:source_url], comment: "", album: @album) rescue nil
        # Redirect to the edit page for that snapshot
        if @snapshot
          redirect_to edit_album_snapshot_path(@album, @snapshot)
        else
          redirect_to @album
        end
      elsif params[:todo] && params[:todo] == "report"
        redirect_to report_album_path(@album)
      else
        redirect_to @album
      end
    else
      render
    end
  end

  # GET /albums/1
  def show
  end

  # GET albums/1/report
  def report
  end

  # POST albums/replace_all_snapshots
  # params:
  #   (album defined by source and user_id)
  #   src_source
  #   src_user_id
  #   dst_source
  #   dst_user_id
  # Replaces content of 'dst' album with content of 'src' album.
  def replace_all_snapshots
    src_token = album_token('src_')
    dst_token = album_token('dst_')
    src_album = Album.find_by(token: src_token)
    if src_token.blank? || dst_token.blank? || src_album.nil?
      render nothing: true, status: 400 and return
    end
    # Source album needs to be present, destination can be dynamically created.
    dst_album = Album.find_or_create_by(token: dst_token)
    dst_album.replace_all_snapshots(src_album)
    render nothing: true, status: 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      if token = album_token
        @album = Album.find_or_create_by(token: token)
      else
        @album = Album.find_by(uuid: params[:id])
      end
    end

    def album_token(prefix = nil)
      source = "#{prefix}source"
      user_id = "#{prefix}user_id"
      if params[source].present? && params[user_id].present?
        Album.token(params[source], params[user_id])
      else
        nil
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :set_snapshot, only: [:show, :edit, :update, :destroy]
  before_action :set_album

  # GET /snapshots/1
  def show
  end

  # GET /snapshots/new
  def new
    @snapshot = Snapshot.new
  end

  # POST /snapshots
  def create
    @snapshot = Snapshot.new(snapshot_params)
    @snapshot.album = @album

    if @snapshot.save
      if request.xhr?
        render json: { edit_path: edit_album_snapshot_path(@album, @snapshot.id) }, content_type: 'text/html'
      else
        redirect_to [@album, @snapshot]
      end
    else
      render action: 'new'
    end
  end

  # GET /snapshots/1/edit
  def edit
  end

  # PATCH/PUT /snapshots/1
  def update
    if @snapshot.update(snapshot_params)
      redirect_to [@album, @snapshot]
    else
      render action: 'edit'
    end
  end

  # DELETE /snapshots/1
  def destroy
    @snapshot.destroy
    redirect_to @album
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snapshot
      @snapshot = Snapshot.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end


    # Only allow a trusted parameter "white list" through.
    def snapshot_params
      params.require(:snapshot).permit(:comment, :content, :annotation, :annotated_snapshot_url)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def snapshot_image_tag(snapshot, size=:medium)
    url = snapshot.content.url(size)
    alt = snapshot.content.original_filename || "missing snapshot"
    image_tag(url, alt: alt, title: alt)
  end
  def annotated_snapshot_image_tag(snapshot, size=:medium)
    return snapshot_image_tag(snapshot, size) unless snapshot.annotated_content.original_filename
    url = snapshot.annotated_content.url(size)
    alt = snapshot.annotated_content.original_filename || "missing snapshot"
    image_tag(url, alt: alt, title: alt)
  end
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/views/albums/index.html.haml
%h1 Failed
%div Failed to find an album! Please make sure you've provided the necessary information.

app/views/albums/report.html.haml
- snapshot_count = @album.snapshots.count
- if snapshot_count == 0
  This album does not contain any snapshots.
- else
  - @album.snapshots.each_with_index do |snapshot, idx|
    .snapshot-report-item
      .report-info
        = "Snapshot #{idx + 1}/#{snapshot_count}"
      = annotated_snapshot_image_tag(snapshot)
      - unless snapshot.comment.blank?
        %hr
        .report-comment
          = snapshot.comment.gsub("\n", "<br/>").html_safe

app/views/albums/show.html.haml
%p#notice= notice
%h1 Snapshots
= render partial: 'snapshots/snapshot_list_item', collection: @album.snapshots, as: :snapshot, locals: { album: @album }
%div
  = link_to 'Add snapshot', new_album_snapshot_path(@album)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Labbook
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "/stylesheets/drawing-tool/drawing-tool", media: "all"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #content
      #inner-content
        = yield

    = javascript_include_tag "/javascripts/drawing-tool-vendor"
    :javascript
      window.drawToolJQuery = $.noConflict();
    = javascript_include_tag "/javascripts/drawing-tool"

app/views/layouts/report.html.haml
!!!
%html
  %head
    %title Labbook
    = stylesheet_link_tag "application", media: "all"
  %body.report-content
    = yield

app/views/snapshots/_form.html.haml
= javascript_include_tag SHUTTERBUG_JS
.snapshot-form
  = form_for([@album, @snapshot], html: { id: "snapshot_form_#{@snapshot.id}"}) do |f|
    .left
      - if @snapshot.persisted?
        .persisted_image{:id => "persisted_image_#{@snapshot.id}"}
        = f.hidden_field :annotation, id: "snapshot_annotation_#{@snapshot.id}"
        = f.hidden_field :annotated_snapshot_url, id: "annotated_snapshot_url_#{@snapshot.id}"

      - unless @snapshot.content.present?
        %div{:style => "min-width: 150px"}
          %span#file-upload-button.fileinput-button
            %span Browse...
            / The file input field used as target for the file upload widget/
            %input#fileupload{:name => "snapshot[content]", :type => "file"}
        #progress{:style => "margin-top: 10px"}
          .bar
    .right
      - if @snapshot.persisted?
        .instructions
          Use the tools on the left to draw on your snapshot. Write your comments in the box below the snapshot and click Save when you are done.
      - if @snapshot.errors.any?
        #error_explanation
          %h2
            = pluralize(@snapshot.errors.count, "error")
            prohibited this snapshot from being saved:
          %ul
            - @snapshot.errors.full_messages.each do |msg|
              %li= msg
              %div
      %h3
        Comments:
      #comments-wrapper
        = f.text_area :comment
      .actions
        = f.submit "Save", class: 'button', id: "snapshot_submit_#{@snapshot.id}"
        = link_to 'Cancel', @album, class: "button", id: "snapshot_cancel_#{@snapshot.id}"

  :javascript
      $(function () {
        var url = "#{@snapshot.persisted? ? album_snapshot_path(@album,@snapshot) : album_snapshots_path(@album)}";
        $('#fileupload').fileupload({
          url: url,
          dataType: 'json',
          add: function (e, data) {
            $('.fileinput-button').hide();
            $('.actions input').prop('disabled', true);
            $('#comments-wrapper .textarea').prop('disabled', true);
            data.submit();
          },
          done: function (e, data) {
            window.location = data.result.edit_path;
          },
          progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .bar').css(
              'width',
              progress + '%'
            );
          },
          fileuploadfail: function(e, data) {
            console.log("Failed!", e, data);
            $('.actions input').prop('disabled', false);
            $('#comments-wrapper .textarea').prop('disabled', false);
          }
        });
      });
      $(document).ready(function() {
        var firstSubmit = true;
        var originalData = "";
        var drawingTool = new DrawingTool("#persisted_image_#{@snapshot.id}", {width: 500, height: 560});
        var drawToolStateHasChanged = function() {
          return originalData != drawingTool.canvas.toDataURL();
        };
        var phone = iframePhone.getIFrameEndpoint();

        // the drawing tool doesn't expose if the document is dirty but it does send events on undoable and redoable actions
        // the first attempt at this kept a counter of undo events (decrementing when 'redo:possible' was received) but since
        // the undo button itself sends a redo:possible event and there is no way to check if there are any other actions
        // on the undo/redo stack, that counter was removed.  A simple flag is now set when anything undoable happens - this isn't
        // ideal as if the user uses the undo button back to a "clean" document LARA will still think it is dirty
        var listenForDrawingChanges = function() {
          drawingTool.on('undo:possible', function () {
            canClose = false;
          })
        };
        var canClose = true;
        var checkIfCanCloseFrom = function (from) {
          if (canClose) {
            phone.post('connected', false);
            if (from === 'phoneHandler') {
              phone.post('close')
            }
            return true;
          }

          $('<div style="padding: 10px; max-width: 500px; word-wrap: break-word;">You have unsaved changes.  Are you sure you want to close?</div>').dialog({
              draggable: false,
              modal: true,
              resizable: false,
              width: 'auto',
              title: 'Confirm',
              minHeight: 75,
              buttons: {
                Yes: function () {
                  canClose = true;
                  phone.post('connected', false);
                  if (from === 'phoneHandler') {
                    phone.post('close');
                  }
                  else if (from === 'cancelButton') {
                    // using .click() on the element doesn't work here so just force the link
                    window.location = $('#snapshot_cancel_#{@snapshot.id}')[0].href;
                  }
                  $(this).dialog('destroy');
                },
                No: function () {
                  $(this).dialog('destroy');
                }
              }
            });

          return false;
        };
        phone.addListener('canClose', function () {
          checkIfCanCloseFrom('phoneHandler');
        });
        phone.initialize();
        phone.post('connected', true);

        $('#snapshot_form_#{@snapshot.id}').submit(function() {
          if (firstSubmit && drawToolStateHasChanged()) {
            var state = JSON.stringify(drawingTool.save());
            $('#snapshot_annotation_#{@snapshot.id}').val(state);
            $(function() {
              var optCallbackFn = function(snap_location) {
                if (snap_location != null) {
                  if (snap_location.indexOf('://') == -1) {
                    snap_location = window.location.protocol + "//" + window.location.host + snap_location;
                  }
                  $("#annotated_snapshot_url_#{@snapshot.id}").val(snap_location);
                }

                firstSubmit = false;
                canClose = true;
                $('#snapshot_form_#{@snapshot.id}').submit();
              };

              $('#snapshot_submit_#{@snapshot.id}').attr('disabled', 'disabled');
              $('#snapshot_submit_#{@snapshot.id}').val('Please wait...');

              drawingTool.clearSelection();

              Shutterbug.snapshot({ selector: "#persisted_image_#{@snapshot.id} .canvas-container", done: optCallbackFn, server: '#{SHUTTERBUG_SERVER}'});
            });
            return false;
          } else {
            return checkIfCanCloseFrom('secondSubmit');
          }
        });

        $('#snapshot_cancel_#{@snapshot.id}').click(function() {
          return checkIfCanCloseFrom('cancelButton');
        });

        var prev_state = $('#snapshot_annotation_#{@snapshot.id}').val();
        if (prev_state) {
          drawingTool.load(JSON.parse(prev_state), function() { originalData = drawingTool.canvas.toDataURL(); listenForDrawingChanges() });
        } else {
          drawingTool.setBackgroundImage("#{@snapshot.content.url(:medium)}", undefined, listenForDrawingChanges);
          originalData = drawingTool.canvas.toDataURL();
        }
      });

app/views/snapshots/_snapshot.html.haml
.snapshot
  .content
    = annotated_snapshot_image_tag(snapshot, :medium)
  .comment
    = snapshot.comment.gsub("\n", "<br/>").html_safe
  .links
    = link_to 'Back to album', album
    |
    = link_to 'Edit',   edit_album_snapshot_path(album, snapshot)
    |
    = link_to 'Delete', album_snapshot_path(album, snapshot), method: :delete, confirm: "Really delete snapshot?"

app/views/snapshots/_snapshot_list_item.html.haml
.snapshot-list-item
  .content
    = link_to annotated_snapshot_image_tag(snapshot, :thumb), album_snapshot_path(album, snapshot)
  .comment
    = snapshot.comment.gsub("\n", "<br/>").html_safe
  .links
    = link_to 'Edit',   edit_album_snapshot_path(album, snapshot)
    |
    = link_to 'Delete', album_snapshot_path(album, snapshot), method: :delete, confirm: "Really delete snapshot?"

app/views/snapshots/edit.html.haml
%h1 Editing snapshot
= render 'form'

app/views/snapshots/new.html.haml
%h1 New snapshot
= render 'form'
= link_to 'Back to album', @album

app/views/snapshots/show.html.haml
= render partial: 'snapshot', locals: { snapshot: @snapshot, album: @album }